### ISSUE TITLE
卒業試験：MVPリリース

### ISSUE THREAD

**Issue by super-appy** [super-appy/itsumono_obento#123]
## 各種情報
いつものお弁当
https://everydaylunchbox-d534442e43a4.herokuapp.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能

- [x] 会員登録
- [x] ログイン
- [x] レシピ生成機能
　・食材、テイスト、時間の3つを入力して検索
- [x] 作りたい（ブックマーク）
- [x] 作ったよ（ブックマーク）
　・リピートしたい
　・メモ
- [x] レシピ一覧機能
　・食材、時間、作ったよ(ブックマーク)数でソート可能
　△ブックマーク数ソートのみ本リリースに持ち越し
- [x] レシピ投稿機能
- [x] お弁当タイムライン機能
　・ログで公開にしたものを一覧でシェア
- [x] いいね機能
- [x] お弁当の記録
- [x] 写真（あれば）、おかずの内容、ひとこと、公開・非公開の設定
- [x] プロフィールの設定

## サービスイメージがわかるようなスクリーンショット等
アプリトップ画面にて説明用に添付しております

宜しくお願い致します。

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。

**Comment by super-appy** [comment]
つちやさん
ご確認いただき、ありがとうございます！
引き続き、宜しくお願い致します。
