### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by super-appy** [super-appy/itsumono_obento#20]
### 機能
- [ ] 会員登録
- [ ] ログイン
- [ ] レシピ生成
- [ ] レシピブックマーク
- [ ] レシピ一覧
- [ ] レシピ投稿
- [ ] お弁当タイムライン
- [ ] タイムラインいいね
- [ ] お弁当の記録
- [ ] プロフィール

### ページ
- [ ] 会員登録(users#new)
- [ ] ログイン(users#login)
- [ ] レシピ生成(recipes#new)
- [ ] レシピ生成結果(recipes#show)
- [ ] レシピ一覧(recipes#index)
- [ ] ブックマーク作ったよ(bookmarked_recipes#edit)
- [ ] ブックマーク一覧(bookmarked_recipes#index)
- [ ] レシピの投稿(recipes#new)
- [ ] レシピのプレビュー(recipes#preview)
- [ ] 投稿したレシピの編集(recipes#edit)
- [ ] お弁当タイムライン(lunchbox_logs#index)
- [ ] お弁当の記録作成(lunchbox_logs#new)
- [ ] お弁当の記録閲覧(lunchbox_logs#show)
- [ ] お弁当の記録編集(lunchbox_logs#edit)
- [ ] プロフィール閲覧(profile#show)
- [ ] プロフィール編集(profile#edit)

**Comment by Tsuchiya2** [comment]
概ね良さそうです。５が付いているものに関しては、開発に取り組む際に、調査・ページ用意・バックエンド実装・etcといったように細かくし直しても大丈夫です。

LGTMです。
